### PR TITLE
SWE64 Dr MacIsaac changes / SWE73 Toastr Notifications not working

### LINKED ISSUE #64: Dr. MacIsaac Changes
## Issue Description
These are the changes Dr. MacIsaac wants to see:

## Tasks
- [x] Change Teacher to Instructor
- [x] Required stars for forms (Course-Name, Start-Date, Rows, and Columns)
- [x] Fix course form validation
- [x] ~~Dropdown for sections in course page~~

### LINKED ISSUE #73: Toastr notifications not working
## Issue Description
Currently the toastr error messages/ success messages are not working. On course form 
## Steps to Reproduce
- Get a validation error on course form (edit or create)
  - You will not see a validation error

## Tasks
- [ ] Fix toastr messages for course creation/ edit

### PR DESCRIPTION
**Pull request by tonerm43**
### Changes Proposed in this Pull Request:
- Add more robust course creation form validation
- UI changes to course list
- Ability to add/view courses that do not have a section
- Fix broken toastr notifications

### Additional Comments and Documentation:
We scrapped the requested change to add a course section dropdown as it would clutter the course form UI, instead we add section to the course list on the side.

### CODE REVIEW

File: src/main/java/com/unb/tracker/model/Course.java [hunk 1]
```diff
@@ -14,9 +14,17 @@
     @Id
     @GeneratedValue(strategy = GenerationType.AUTO)
     private Long id;
-    private String timeSlot;
+
```
Comment (tonerm43) [inline src/main/java/com/unb/tracker/model/Course.java]: Does anyone know if these comments still need to be here? They were pulled in from a merge conflict

Comment (dsteen338) [reply src/main/java/com/unb/tracker/model/Course.java]: I don't think so.... I left it there cause I wasn't sure

File: src/main/resources/static/js/courseform.js [hunk 2]
```diff
@@ -3,6 +3,17 @@ $(document).ready(function() {
...
+
+        if(document.forms["courseForm"]["section"] == "") {
+            document.forms["courseForm"]["section"] = null;
+        }
+
+        if(document.forms["courseForm"]["startDate"].value == ""){
+            document.forms["courseForm"]["startDate"].value = "1970-01-01";
+        }
+    });
+
```
Comment (tonerm43) [inline src/main/resources/static/js/courseform.js]: These are kind of an ugly solution, but empty fields get parsed as empty strings when they are sent to the server which produces a 400 error for these fields. If we send some garbage data however, we can get around this. Does anyone know a less hacky solution for this?

File: src/main/resources/templates/courseFormView.twig [hunk 3]
```diff
@@ -1,32 +1,30 @@
...
         </div>
         <div class="md-form">
-            <input placeholder="End Date" name="endDate" type="text" class="form-control datepicker" >
-        </div>
-        <div class="md-form">
-            <input id="course-form-rows" placeholder="Rows" name="rows" type="number" class="form-control" {% if courseCreationError %}value="{{ rowsAmount }}"{% endif %}>
-        </div>
-        <div class="md-form">
-            <input id="course-form-cols" placeholder="Columns" name="cols" type="number" class="form-control" {% if courseCreationError %}value="{{ colsAmount }}"{% endif %}>
+            <input id="course-form-cols" placeholder="Columns (Required)" name="cols" type="number" class="form-control" {% if courseCreationError %}value="{{ colsAmount }}"{% endif %}>
```
Comment (MackenzieJones) [inline src/main/resources/templates/courseFormView.twig]: What if we have an "(optional)" for section instead of a "(required)" for name, date, rows, and cols?

Comment (tonerm43) [reply src/main/resources/templates/courseFormView.twig]: I like this idea

File: src/main/java/com/unb/tracker/validator/CourseValidator.java [hunk 4]
```diff
@@ -21,11 +22,35 @@ public boolean supports(Class<?> aClass) {
...
+        if (!courseService.findByInstructorUsernameAndNameAndSection(course.getInstructor().getUsername(), course.getName(), course.getSection()).isEmpty()) {
+            errors.rejectValue("name", "This section for this course already exists.");
+        }
+
+        if (course.getStartDate().toString().equals("1970-01-01")) {
+            errors.rejectValue("startDate", "Ensure all required fields are filled. (Check Start Date)");
+        }
+
+        if (course.getName().length() > 10) {
+            errors.rejectValue("name", "Course name should be less than 10 characters");
```
Comment (brandon1024) [inline src/main/java/com/unb/tracker/validator/CourseValidator.java]: Have we decided that we are going to limit the course name and section name to 10 characters? I still think we should just truncate with CSS, but if PO @mwalz1 wants this, I'll live ;)

File: src/main/resources/templates/courselist.twig [hunk 5]
```diff
@@ -4,8 +4,8 @@
     <div class="list-group courselist">
         <p class="list-group-item active">Course List</p>
         {% for course in courseList %}
-            <a href="/{{ course.instructor.username }}/{{ course.name }}{% if course.section %}/{{ course.section }}{% endif %}"
-               class="list-group-item courselist-item">{{ course.getName() }}</a>
+            <a href="/{{ course.instructor.username }}/{{ course.name }}{% if course.getSection.equals("") %} {% else %}/{{ course.section }}{% endif %}"
+               class="list-group-item courselist-item">{{ course.getName() }}{% if course.getSection.equals("") %} {% else %} - {{ course.getSection() }}{% endif %}</a>
```
Comment (brandon1024) [inline src/main/resources/templates/courselist.twig:8]: could you not use negation instead?

`{% if not course.getSection.equals("") %}{{ course.getSection() }}{% endif %}`

File: src/main/java/com/unb/tracker/validator/CourseValidator.java (hunk 4 above)
Comment (tonerm43) [reply src/main/java/com/unb/tracker/validator/CourseValidator.java]: This was specified by MacIsaac

File: src/main/resources/templates/courselist.twig (hunk 5 above)
Comment (tonerm43) [reply src/main/resources/templates/courselist.twig:8]: We had this originally, but it did not work. We also tried 
`{% if !course.getSection.equals("") %}{{ course.getSection() }}{% endif %}` 
which did not work either

File: src/main/java/com/unb/tracker/web/CourseController.java [hunk 6]
```diff
@@ -125,31 +125,43 @@ public String courseSave(@ModelAttribute Course course, Model model, Principal p
...
         }
+        course.setInstructor(user);
 
         courseValidator.validate(course, bindingResult);
         if (bindingResult.hasErrors()) {
             redir.addFlashAttribute("courseCreationError", bindingResult.getFieldError().getCode());
             redir.addFlashAttribute("courseName", course.getName());
             redir.addFlashAttribute("sectionName", course.getSection());
-            redir.addFlashAttribute("startDate", course.getStartDate().toString());
+            if(course.getStartDate().toString().equals("1970-01-01")) {
```
Comment (dsteen338) [inline src/main/java/com/unb/tracker/web/CourseController.java]: Is there something somewhere that converts empty value to the beginning of Unix time or something?

EDIT: Nvm saw further down

File: src/main/resources/static/js/courseform.js (hunk 2 above)
Comment (dsteen338) [reply src/main/resources/static/js/courseform.js]: I'm not sure what you mean by this, do you mean you get a 400 if you try to submit with an empty date?

Also, it doesn't really matter but we've been mostly sticking to jquery for stuff like those selectors... although the pure js is nicer. This should be the jquery equivalent (I believe): ` $('input#fieldName').val();`

I'm really torn on whether or not you should change this

File: src/main/resources/templates/courseFormView.twig [hunk 7]
```diff
@@ -1,32 +1,30 @@
 {% if courseCreationError %}
+    <script type="text/javascript" src="/static/js/jquery-3.2.1.min.js"></script>
```
Comment (dsteen338) [inline src/main/resources/templates/courseFormView.twig:2]: Is this necessary?.... There has to be a better way to do this

**Review by dsteen338 — CHANGES_REQUESTED** [review]
Mostly just questions

File: src/main/resources/templates/courseFormView.twig (hunk 7 above)
Comment (tonerm43) [reply src/main/resources/templates/courseFormView.twig:2]: I believe @brandon1024 's PR addresses this. Basically we are trying to use some javascript before it gets brought into the file, so here I just put everything in the file. It's ugly, but it works

**Review by mwalz1 — APPROVED** [review]
Meets all Requirements.  Looks good and easy to use.  The toastrs were a great addition.

File: src/main/resources/templates/courselist.twig (hunk 5 above)
Comment (brandon1024) [reply src/main/resources/templates/courselist.twig:8]: Could it be be because you're using `getSection` and not `getSection()`?

Why not do this for the first one? `{{ course.getSection() }}`? If the section is empty, it will just inject the empty string, which is fine.

For the second one, we can just do this (the `-` isn't super necessary): `{{ course.getSection() }}`

File: src/main/resources/templates/courseFormView.twig (hunk 7 above)
Comment (dsteen338) [reply src/main/resources/templates/courseFormView.twig:2]: I guess that's fine then.

**Comment by dsteen338** [comment]
@tonerm43 Once merge conflicts are resolved I think this is ready to merge

**Review by MackenzieJones — APPROVED** [review]

**Review by dsteen338 — APPROVED** [review]

**Comment by dsteen338** [comment]
Looks good, all couldn't find any issues

**Comment by dsteen338** [comment]
Seems good to merge, right?
