### PR TITLE
Swe60 row and column validation

### LINKED ISSUE #60: Rows & Columns Validation
## Issue Description
An instructor is able to set the rows and cols of the course to zero.

## Steps to Reproduce
- Login as an instructor
- Create a course with negative rows or cols

## Tasks
- [x] Add validation in the backend
- [x] Set minimum value for row and cols in the frontend

### PR DESCRIPTION
**Pull request by tonerm43**
### Changes Proposed in this Pull Request:
- Set upper and lower bounds on course creation form for rows and columns

### Additional Comments and Documentation:
- Further validation for this form will be in #64

### CODE REVIEW

File: src/main/java/com/unb/tracker/validator/CourseValidator.java [hunk 1]
```diff
@@ -0,0 +1,33 @@
...
+    @Override
+    public boolean supports(Class<?> aClass) {
+        return Course.class.equals(aClass);
+    }
+
+    @Override
+    public void validate(Object o, Errors errors) {
+        Course course = (Course) o;
+
+        if (course.getRows() < 1 || course.getRows() > 18) {
```
Comment (JoshuaKirby) [inline src/main/java/com/unb/tracker/validator/CourseValidator.java:24]: Should these values be pulled out into a config file? I'm not sure how it would be done but it might save some headaches later

File: src/main/resources/templates/courseFormView.twig [hunk 2]
```diff
@@ -1,31 +1,32 @@
-<div style="width:50%; margin: auto; padding-bottom: 60px;" class="collapse" id="courseForm">
+{% if courseCreationError %}<script>toastr.error("{{ courseCreationError }}")</script>{% endif %}
+<div style="width:50%; margin: auto; padding-bottom: 60px;" class="{% if not courseCreationError %}collapse{% endif %}" id="courseForm">
     <form action="/course" method="post">
         <div class="md-form">
-            <input placeholder="Course Name" type="text" name="name" class="form-control" id="courseFormName">
+            <input placeholder="Course Name" type="text" name="name" class="form-control" id="courseFormName"{% if courseCreationError %}value="{{ courseName }}"{% endif %}>
```
Comment (JoshuaKirby) [inline src/main/resources/templates/courseFormView.twig:11]: Would we be able to pull in a js package so we don't have to manage the return values on error ourselves? Not sure if that's available

File: src/main/resources/templates/dashboard.twig [hunk 3]
```diff
@@ -39,9 +44,18 @@
                     </script>
                     {% endblock %}
                     <p>Select a course from the course list, or create a course.</p>
-                    <button type="button" data-target="#courseForm" class="btn btn-primary" data-toggle="collapse"
-                            aria-expanded="false" aria-controls="courseForm">Create Course
-                    </button>
+                    {% if courseCreationError %}
```
Comment (JoshuaKirby) [inline src/main/resources/templates/dashboard.twig]: The branches of this if are identical, is it the aria-expanded value supposed to be changed?

**Review by JoshuaKirby — COMMENTED** [review]
I have some questions about different parts.

File: src/main/java/com/unb/tracker/validator/CourseValidator.java (hunk 1 above)
Comment (mwalz1) [reply src/main/java/com/unb/tracker/validator/CourseValidator.java:24]: I +1 this idea but believe it should be looked after in some sort of improvement issue.

**Review by mwalz1 — CHANGES_REQUESTED** [review]
Two invalid submissions in a row cause the page to be redirected to a 404.

File: src/main/resources/templates/dashboard.twig (hunk 3 above)
Comment (tonerm43) [reply src/main/resources/templates/dashboard.twig]: Nope, we thought we were going to have to do something here, and forgot to revert this part.

**Comment by tonerm43** [comment]
@mwalz1 Make sure that you re-enter the data for Start/End dates and time slot before you re-submit. We did this many times while testing and it causes 404. We will fix this in #64 so it puts back data for start date as that issue requires more form validation for the course form and is probably out  of scope for this issue.

**Review by mwalz1 — APPROVED** [review]

File: src/main/java/com/unb/tracker/service/CourseServiceImpl.java [hunk 4]
```diff
@@ -0,0 +1,28 @@
...
+import org.springframework.beans.factory.annotation.Autowired;
+import org.springframework.stereotype.Service;
+
+@Service
+public class CourseServiceImpl implements CourseService {
+    @Autowired
+    private CourseRepository courseRepository;
+
+    @Override
+    public void save(Course course) {
```
Comment (MackenzieJones) [inline src/main/java/com/unb/tracker/service/CourseServiceImpl.java:14]: Why do you set the things to themselves?

**Review by MackenzieJones — CHANGES_REQUESTED** [review]
Could you add some tests for the validation?

File: src/main/java/com/unb/tracker/service/CourseServiceImpl.java (hunk 4 above)
Comment (tonerm43) [reply src/main/java/com/unb/tracker/service/CourseServiceImpl.java:14]: All I did here was mirror what was written in the `UserServiceImpl` class. Not even sure that this class is necessary, can you confirm this? @brandon1024 @dsteen338

Comment (brandon1024) [reply src/main/java/com/unb/tracker/service/CourseServiceImpl.java:14]: I don't believe this is needed

**Review by jsmith — CHANGES_REQUESTED** [review]
Once you add a few tests this should be good!

File: src/main/java/com/unb/tracker/validator/CourseValidator.java (hunk 1 above)
Comment (brandon1024) [reply src/main/java/com/unb/tracker/validator/CourseValidator.java:24]: I agree with mike. I was going to do a similar thing in the auth issue, but didn't get around to it. We could create an issue to do this for all types of validation--user and course.

File: src/main/java/com/unb/tracker/service/CourseServiceImpl.java (hunk 4 above)
Comment (tonerm43) [reply src/main/java/com/unb/tracker/service/CourseServiceImpl.java:14]: Without this file, the app is unable to start. It says `Field courseService in com.unb.tracker.validator.CourseValidator required a bean of type 'com.unb.tracker.service.CourseService' that could not be found.`

File: src/main/resources/templates/index.twig [hunk 5]
```diff
@@ -120,7 +120,7 @@
                     </div>
                     <div id="index-button-container">
                         <button id="student-login-button" type="button" class="btn btn-primary">I'm a Student</button>
-                        <button id="instructor-login-button" type="button" class="btn btn-primary">I'm a Teacher
+                        <button id="instructor-login-button" type="button" class="btn btn-primary">I'm an Instructor
```
Comment (tonerm43) [inline src/main/resources/templates/index.twig:123]: This change was actually requested in #64, but we've added it here for demo purposes.

**Review by jsmith — APPROVED** [review]

**Review by MackenzieJones — APPROVED** [review]
